Fix Wbitwise-instead-of-logical introduced by clang-r445002
Bug: http://b/215753485

packages/apps/Nfc/nci/jni/NativeNfcTag.cpp:1466:22: error: use of
bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]
    isFormattable = (NfcTag::getInstance().isMifareUltralight() |
                    ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
packages/apps/Nfc/nci/jni/NativeNfcTag.cpp:1466:22: note: cast one or
both operands to int to silence this warning

Test: Build with new clang
Change-Id: Iaafa695751ef8626486836bf5d78899459dd152f